### ISSUE TITLE
show badges

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/pipeline-agent-build-history-plugin#47]
### What feature do you want to see added?

badges are shown in the build history widget. This could be a valuable information to be shown on a jobs history page

**Comment by ganesh-sadanala** [comment]
working on it

**Comment by mawinter69** [comment]
beware that this task is not newby friendly

**Comment by ganesh-sadanala** [comment]
Is this a bug? Jenkins cannot verify the agent, so the agent can't connect to the controller. All the configuration is correct and no network or firewall blocking. Can access Jenkins from UI and curl, but 'agent-1' can't connect to it. I am currently working on the https://github.com/jenkinsci/pipeline-agent-build-history-plugin/issues/47 My Jenkins instance is from the build of the above Repo using mvn hpi:run. Java version: 17 LTS . Instance identity is generated by Jenkins, but when executed, it is throwing invalid X-instance-identity. Have been working on this for 2 days, to see if I am making any mistake, but issue is on the jenkins
@mawinter69 
<img width="666" alt="Screenshot 2024-05-25 at 3 01 27 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/211eca2c-b28b-4cf2-b2bd-9a85713350c6">
<img width="476" alt="Screenshot 2024-05-25 at 3 01 09 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/6d546db6-e1ba-47a9-b3b0-85bc3f092a44">
<img width="1440" alt="Screenshot 2024-05-25 at 3 00 49 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/fd463311-37e3-430a-abe4-9ceb71d72bc3">
<img width="1438" alt="Screenshot 2024-05-25 at 3 00 44 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/d409e86a-22a8-456e-8f1d-0bb6c39a956a">
<img width="599" alt="Screenshot 2024-05-25 at 3 00 38 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/6534c59e-4b2e-4d19-8b9f-49fdeeb30abd">
<img width="588" alt="Screenshot 2024-05-25 at 3 00 24 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/61a1d3a1-cbfe-4a18-95e0-7b5978649538">
```
gsadanala@Ganeshs-Air jenkins % java -jar agent.jar -url http://localhost:8080/jenkins/ -secret 8e54e781cd66c7f7605838caf360418b41cd556245a2f07d2709b310118b253f -name "agent-1" -workDir "/Users/gsadanala/jenkins"
May 25, 2024 2:37:45 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /Users/gsadanala/jenkins/remoting as a remoting work directory
May 25, 2024 2:37:45 PM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /Users/gsadanala/jenkins/remoting
May 25, 2024 2:37:45 PM hudson.remoting.Launcher createEngine
INFO: Setting up agent: agent-1
May 25, 2024 2:37:45 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3206.vb_15dcf73f6a_9
May 25, 2024 2:37:45 PM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /Users/gsadanala/jenkins/remoting as a remoting work directory
May 25, 2024 2:37:45 PM hudson.remoting.Launcher$CuiListener status
INFO: Locating server among [http://localhost:8080/jenkins/]
May 25, 2024 2:37:45 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
May 25, 2024 2:37:45 PM hudson.remoting.Launcher$CuiListener status
INFO: Could not locate server among [http://localhost:8080/jenkins/]; waiting 10 seconds before retry
java.io.IOException: http://localhost:8080/jenkins/tcpSlaveAgentListener/ appears to be publishing an invalid X-Instance-Identity.
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:277)
	at hudson.remoting.Engine.innerRun(Engine.java:809)
	at hudson.remoting.Engine.run(Engine.java:563)
```

**Comment by mawinter69** [comment]
Hard to tell if this is a bug anywhere but unlikely. I don't use inbound agents (usually I have outbound with ssh) and for development I usually use the [Mock-Agent](https://plugins.jenkins.io/mock-slave/) plugin

**Comment by mawinter69** [comment]
Can you try to add  `-webSocket ` to the java process
```
java -jar agent.jar -url http://localhost:8080/jenkins/ -secret 8e54e781cd66c7f7605838caf360418b41cd556245a2f07d2709b310118b253f -name "agent-1" -workDir "/Users/gsadanala/jenkins"  -webSocket 
```

**Comment by ganesh-sadanala** [comment]
> Can you try to add `-webSocket ` to the java process
> 
> ```
> java -jar agent.jar -url http://localhost:8080/jenkins/ -secret 8e54e781cd66c7f7605838caf360418b41cd556245a2f07d2709b310118b253f -name "agent-1" -workDir "/Users/gsadanala/jenkins"  -webSocket 
> ```

Websocket connection worked. Amazing! So is this a bug? It would be better to provide this as an option to use for traditional TCP/IP connection. Thanks!

**Comment by ganesh-sadanala** [comment]
<img width="832" alt="Screenshot 2024-05-25 at 5 49 57 PM" src="https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/40536512/883b2112-9977-4880-ac9e-86fd2f2dd63a">
@mawinter69 Just a small clarification. I am assuming that "badges" here means icons that need to be added for example beside: Failure, Success in the attached Extended Build History of the agent. Please correct me if I am wrong. Thanks for the Mock-Agent plugin suggestion!

**Comment by mawinter69** [comment]
I meant the icons you can see in the history widget of a job
![image](https://github.com/jenkinsci/pipeline-agent-build-history-plugin/assets/17767050/bf323368-6d8f-42f1-9daf-3288e9a87d25)
Currently the progressive rendering is working by sending json data to javascript and then in javascript the html is generated. 
But the badges contain inline svgs so this would mean to transfer bigger amount of data and potentially also duplicate data.
For an easier integration both extended history pages would need to switch away from the progressive rendering approach to a direct approach where everything is done within jelly. That is a bigger change (any why I said it is not newby friendly).

**Comment by mawinter69** [comment]
partially solved with #50 for the job history
